name: CI/CD Flowless

on:
  push:
    branches:
      - dev

jobs:
  Copy_Code_and_deploy_the_website:
    runs-on: self-hosted

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'

      - name: Set up environment
        run: |
          echo "CODE_PATH=/home/ubuntu/floless-website" >> $GITHUB_ENV

      - name: SSH and Pull Code on EC2
        run: |
          # Write the SSH key from GitHub Secrets to a file
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
          chmod 600 ssh_key.pem
          
          # SSH into the EC2 instance
          ssh -i ssh_key.pem -o StrictHostKeyChecking=no ubuntu@35.154.244.198 << 'ENDSSH'
          # Navigate to the cloned repository directory
          cd $CODE_PATH
          # Pull the latest code from the repository
          git pull origin dev
          # Exit the SSH session
          ENDSSH

      - name: install dependencies
        run: |
          cd $CODE_PATH && npm install
      
      - name: npm build
        run: |
          cd $CODE_PATH && npm run build

      - name: pm2 start and restart
        run: |
          cd $CODE_PATH && pm2 start npm --name floless-website -- start || pm2 restart website
